# Create main category associated with each sub-category
category_dict = {
    'Electronics':'Occasional Expense',
    'Liquor Store':'Discretionary Spending',
    'Refund':'Income',
    'Restaurants':'Discretionary Spending',
    'Subscriptions':'Discretionary Spending',
    'Goods':'Discretionary Spending',
    'Cash Back Rewards':'Income',
    'Reimbursement':'Income',
    'Work Lunch & Takeout':'Discretionary Spending',
    'Medical & Health':'Living Expense',
    'Home Supplies':'Living Expense',
    'Laundromat':'Living Expense',
    'Shipping':'Living Expense',
    'Groceries':'Living Expense',
    'Transportation':'Living Expense',
    'Internet':'Monthly Bills',
    'Utilities':'Monthly Bills',
    'Clothing':'Discretionary Spending',
    'Entertainment':'Discretionary Spending',
    'Tools':'Living Expense',
    'Interest Income':'Income',
    'Rent':'Monthly Bills',
    'Income':'Income',
    'Appliances':'Occasional Expense',
    'Home Insurance':'Occasional Expense',
    'Furniture':'Occasional Expense',
    'Tax Refund':'Income',
    'Air Travel':'Occasional Expense',
    'Personal Care':'Discretionary Spending',
    'Taxes':'Occasional Expense',
    'Home Decor':'Discretionary Spending',
    'Service Fee':'Occasional Expense',
    'Hotel':'Occasional Expense',
    'Gift':'Occasional Expense',
    'Shopping':'Discretionary Spending',
    'Mobile Phone':'Monthly Bills',
    'ATM Fee':'Living Expense',
    'Business Services':'Monthly Bills',
    'Cash & ATM':'Living Expense',
    'Vacation': 'Occasional Expense',
    'Investment - Source 1': 'Savings',
    'Investment - Source 2': 'Savings',
    'Paycheck - Source 1': 'Income',
    'Paycheck - Source 2': 'Income'
}